apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: kubelet-extra-labels-infra
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
